version: '3.8'
services:
  painel-advocacia:
    build:
      context: .
      dockerfile: Dockerfile
    image: alves-martins-painel:latest
    container_name: alves-martins-painel
    restart: always
    # Substituímos o 'ports' pelo 'expose' para não entrar em conflito com o proxy do Coolify
    expose:
      - "80"
    volumes:
      - ./vps-data:/app/data
